[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "orbit"
readme  = "README.md"

# TODO: Change your package specifications
# -----------------------------------------------------------------
title = "Extension Template"
author = "ORBIT Project Developers"
maintainer = "Nico Burger"
maintainer_email = "nburger@theaiinstitute.com"
description="Extension Template for Orbit"
repository = "https://github.com/isaac-orbit/orbit.ext_template.git"
keywords = ["extension", "template", "orbit"]
# -----------------------------------------------------------------

[dependencies]
"omni.isaac.orbit" = {}
"omni.isaac.orbit_assets" = {}
"omni.isaac.orbit_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
# TODO: Change your package name
# -----------------------------------------------------------------
name = "orbit.ext_template"
# -----------------------------------------------------------------
